displayName=Webweaver Swap
author=ftwpk
support=https://github.com/Ftwpker/webweaver-swap-plugin
description=Swap Webweaver bow visuals to Craw's bow.
tags=webweaver,craw,bow,ranged
plugins=com.webweaverswap.WebweaverSwapPlugin
